[phases.setup]
nixPkgs = ["php82", "php82Extensions.mongodb", "php82Extensions.redis", "apacheHttpd"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "apache2ctl -D FOREGROUND"